### ISSUE TITLE
Git LFS

### ISSUE THREAD

**Issue by pitdicker** [chronotope/pure-rust-locales#13]
I may be naive, consider this just a question.

This repo is using Git LFS for the `lib.rs` file. I can't review the changes in Git Gui or on GitHub, and have to manually diff against the copy of an older version. The reason is that LFS is primarily intended for [large blobs of binary data](https://github.com/git-lfs/git-lfs/issues/2498).

What do we think about converting it to a regular Git file? And (maybe this is cursing) how about doing this conversion over the git history?

**Comment by cecton** [comment]
I think it's fine on text files anyway. I was probably too cautious when I did it.

**Comment by djc** [comment]
Sounds like that would be an improvement.

**Comment by pitdicker** [comment]
Then I think the steps would be to remove branch protection from main for a moment, do `git lfs migrate export --everything`, and force push.
Documentation: https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.adoc.

**Comment by djc** [comment]
Hmm, I think we should probably not rewrite history for this.
