### ISSUE TITLE
Implement `FromStr` for locale.

### ISSUE THREAD

**Issue by gibbz00** [chronotope/pure-rust-locales#9]
Having a hard time coming up with a strong motivation other than it's usually what I expect from simpler `&str` to have been implemented. 

Should simple to implement by calling `TryFrom<&str>` internally.

**Comment by cecton** [comment]
It's already there: https://github.com/chronotope/pure-rust-locales/blob/main/generate-api/src/generator.rs#L519

Or am I missing something?

**Comment by gibbz00** [comment]
Almost! `FromStr` and `TryFrom<&str>` are different traits, the latter is more general, but they achieve the same thing in the end. (Hence the allusion that it might not be worth implementing, other than possibly saving end users a round trip to the docs.)

```rust
let locale_0 = Locale::try_from("en_US"); // TryFrom
let locale_1 = "en_US".parse::<Locale>() // FromStr
```

```rust
impl FromStr for Locale {
    type Err = UnknownLocale;

    fn from_str(str: &str) -> Result<Self, Self::Err> {
        Locale::try_from(str)
    }
}
```

**Comment by cecton** [comment]
hahaha my brain did a shortcut sorry! I think I can add it via GitHub directly because it's so simple
